In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [7]:
df=pd.read_csv('/content/fraud_detection.csv')

In [9]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0.0,0.0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0.0,0.0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0.0,0.0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0.0,0.0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0.0,0.0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0.0,0.0

In [12]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97225 entries, 0 to 97224
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            97225 non-null  int64
 1   type            97225 non-null  object
 2   amount          97225 non-null  float64
 3   nameOrig        97225 non-null  object
 4   oldbalanceOrg   97225 non-null  float64
 5   newbalanceOrig  97225 non-null  float64
 6   nameDest        97225 non-null  object
 7   oldbalanceDest  97225 non-null  float64
 8   newbalanceDest  97224 non-null  float64
 9   isFraud         97224 non-null  float64
 10  isFlaggedFraud  97224 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 8.2+ MB

In [14]:
df['step'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [17]:
df.shape

(97225, 11)

In [18]:
df['type'].unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [20]:
type=df['type'].value_counts()

In [22]:
transaction=type.index

In [24]:
quantity=type.values

In [25]:
import plotly.express as px

In [27]:
px.pie(df, values=quantity,names=transaction,hole=0.3,title="Pie Chart Showing Types of Transaction")

In [28]:
df=df.dropna()

In [29]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
97219,10,PAYMENT,10811.91,C504389296,1009.0,0.00,M1318927100,0.0,0.0,0.0,0.0
97220,10,PAYMENT,17011.46,C1283088834,0.0,0.00,M485693121,0.0,0.0,0.0,0.0
97221,10,PAYMENT,1680.50,C671281,0.0,0.00,M661110294,0.0,0.0,0.0,0.0
97222,10,PAYMENT,26450.83,C948744009,0.0,0.00,M1020130183,0.0,0.0,0.0,0.0
97223,10,PAYMENT,12171.47,C1843902873,0.0,0.00,M2011839805,0.0,0.0,0.0,0.0

In [35]:
df.replace(to_replace=['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],value=[1,4,2,5,3],inplace=True)

In [36]:
type

PAYMENT     38478
CASH_OUT    29839
CASH_IN     19561
TRANSFER     8371
DEBIT         976
Name: type, dtype: int64

In [37]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,2,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
97219,10,1,10811.91,C504389296,1009.0,0.00,M1318927100,0.0,0.0,0.0,0.0
97220,10,1,17011.46,C1283088834,0.0,0.00,M485693121,0.0,0.0,0.0,0.0
97221,10,1,1680.50,C671281,0.0,0.00,M661110294,0.0,0.0,0.0,0.0
97222,10,1,26450.83,C948744009,0.0,0.00,M1020130183,0.0,0.0,0.0,0.0
97223,10,1,12171.47,C1843902873,0.0,0.00,M2011839805,0.0,0.0,0.0,0.0

In [38]:
df['isFraud']=df['isFraud'].map({0:'NO Fraud',1:'FRAUD'})

In [39]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,NO Fraud,0.0
1,1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,NO Fraud,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,FRAUD,0.0
3,1,2,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,FRAUD,0.0
4,1,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,NO Fraud,0.0
...,...,...,...,...,...,...,...,...,...,...,...
97219,10,1,10811.91,C504389296,1009.0,0.00,M1318927100,0.0,0.0,NO Fraud,0.0
97220,10,1,17011.46,C1283088834,0.0,0.00,M485693121,0.0,0.0,NO Fraud,0.0
97221,10,1,1680.50,C671281,0.0,0.00,M661110294,0.0,0.0,NO Fraud,0.0
97222,10,1,26450.83,C948744009,0.0,0.00,M1020130183,0.0,0.0,NO Fraud,0.0
97223,10,1,12171.47,C1843902873,0.0,0.00,M2011839805,0.0,0.0,NO Fraud,0.0

In [40]:
x=df[['type','amount','oldbalanceOrg','newbalanceOrig']]

In [41]:
y=df.iloc[:,-2]

In [42]:
y

0        NO Fraud
1        NO Fraud
2           FRAUD
3           FRAUD
4        NO Fraud
           ...
97219    NO Fraud
97220    NO Fraud
97221    NO Fraud
97222    NO Fraud
97223    NO Fraud
Name: isFraud, Length: 97224, dtype: object

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2, random_state=42)

In [44]:
model=DecisionTreeClassifier()

In [46]:
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [49]:
model.score(xtest,ytest)

0.9990743121625096

In [51]:
model.predict([[2,98451,14589,45789]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names

array(['NO Fraud'], dtype=object)

In [50]:
x

       type    amount  oldbalanceOrg  newbalanceOrig
0         1   9839.64       170136.0       160296.36
1         1   1864.28        21249.0        19384.72
2         4    181.00          181.0            0.00
3         2    181.00          181.0            0.00
4         1  11668.14        41554.0        29885.86
...     ...       ...            ...             ...
97219     1  10811.91         1009.0            0.00
97220     1  17011.46            0.0            0.00
97221     1   1680.50            0.0            0.00
97222     1  26450.83            0.0            0.00
97223     1  12171.47            0.0            0.00

[97224 rows x 4 columns]